// 6502 WASM accelerator bridge for RetroAppleJS
// Derived from tools/6502_WASM_Runner.html.
// The WASM core owns a private flat 64 KiB image while active.  The JavaScript
// emulator is paused during the handoff; main RAM and CPU registers are copied
// back before the JavaScript CPU resumes.

if(typeof(oEMU)==="undefined") var oEMU={"component":{"CPU":{}}};
else if(!oEMU.component) oEMU.component={"CPU":{}};
else if(!oEMU.component.CPU) oEMU.component.CPU={};

oEMU.component.CPU.WASM6502 = new EMU_WASMcpu6502();

function EMU_WASMcpu6502()
{
    var self=this;

    const WASM_BASE64='AGFzbQEAAAABGARgAAF/YAh/f39/f39/fwBgAABgAX8BfwMQDwABAgICAAAAAAAAAAAAAwQFAXABAQEFAwEAAgYIAX8BQaCoBAsH+QEQBm1lbW9yeQIAC2dldF9yYW1fcHRyAAANY3B1X3NldF9zdGF0ZQABCWNwdV9yZXNldAACEGNwdV9yZXF1ZXN0X3N0b3AAAw5jcHVfY2xlYXJfc3RvcAAECmNwdV9nZXRfcGMABQljcHVfZ2V0X2EABgljcHVfZ2V0X3gABwljcHVfZ2V0X3kACApjcHVfZ2V0X3NwAAkJY3B1X2dldF9wAAoTY3B1X2dldF9sYXN0X29wY29kZQALFmNwdV9nZXRfbGFzdF9vcGNvZGVfcGMADBVjcHVfZ2V0X2xhc3RfZXhlY3V0ZWQADQ1jcHVfcnVuX2NodW5rAA4KlZgBDwgAQZCIgIAAC2sAQQAgAToAkoiEgABBACAAOwGQiISAAEEAIAI6AJOIhIAAQQAgAzoAlIiEgABBACAEOgCViISAAEEAIAY7AYCIgIAAQQAgBUEgcjoAloiEgABBACAHQQBHOgCCiICAAEEAQQA6AJeIhIAAC1cAQQBB/QE6AJWIhIAAQQBBJDoAloiEgABBAEEALwGMiISAADsBkIiEgABBAEEAOgCTiISAAEEAQQA6AJSIhIAAQQBBADoAkoiEgABBAEEAOgCXiISAAAsNAEEAQQE6AJeIhIAACw0AQQBBADoAl4iEgAALCwBBAC8BkIiEgAALCwBBAC0AkoiEgAALCwBBAC0Ak4iEgAALCwBBAC0AlIiEgAALCwBBAC0AlYiEgAALCwBBAC0AloiEgAALCwBBAC0AmIiEgAALCwBBAC8BmoiEgAALCwBBACgCnIiEgAALvJUBAQd/AkAgAA0AQQAgADYCnIiEgABBAA8LQQAhAQJAA0ACQEEALQCXiISAAEUNAEEAIAE2ApyIhIAAQQIPCwJAQQAtAIKIgIAARQ0AQQAvAZCIhIAAQQAvAYCIgIAARw0AQQAgATYCnIiEgABBAQ8LQQBBAC8BkIiEgAAiAjsBmoiEgABBACACQQFqIgM7AZCIhIAAQQAgAkGQiICAAGotAAAiBDoAmIiEgAAgBEH/AUYNAQJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAQO/wGKAQaYAZgBmAEBaJgBjQEAZ5gBmAEDapgBfQeYAZgBmAECaZgBjwEFmAGYAZgBBGuYAYcBDpgBmAF7CXKYAY4BCHGYAXwLdJgBfg+YAZgBmAEKc5gBkAENmAGYAZgBDHWYAYkBFpgBmAGYARFtmAGLARBsmAGFARNvmAF/F5gBmAGYARJumAGRARWYAZgBmAEUcJgBiAEemAGYAZgBGXeYAYwBGHaYAYYBG3mYAYABH5gBmAGYARp4mAGSAR2YAZgBmAEcepgBmAFNmAGYAVJIT5gBZpgBVpgBVEpRmAGBAU6YAZgBU0lQmAFYTFqYAZgBS5gBmAFDPD6YAUQ3P5gBVzZVmAFGOUGYAYIBPZgBmAFFOECYAZMBO1mYAUc6QpgBMy6YAZgBNClfmAFlKGSYATUrYZgBgwEvmAGYAZgBKmCYAZQBLZgBmAGYASximAEwJpgBmAExIVuYAWMglgGYATIjXZgBhAEnmAGYAZgBIlyYAZUBJZgBmAGYASReigELQQAgAkECajsBkIiEgABBAEEALQCSiISAACADQf//A3FBkIiAgABqLQAAciICOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMlQELQQAgAkECajsBkIiEgABBAEEALQCSiISAACADQf//A3FBkIiAgABqLQAAQZCIgIAAai0AAHIiAjoAkoiEgABBACACQf8BcUVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADJQBC0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgABBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGpB/wFxQZCIgIAAai0AAHIiAjoAkoiEgABBACACQf8BcUVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADJMBC0EAIAJBA2o7AZCIhIAAQQBBAC0AkoiEgAAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckGQiICAAGotAAByIgI6AJKIhIAAQQAgAkH/AXFFQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAySAQtBACACQQNqOwGQiISAAEEAQQAtAJKIhIAAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0Ak4iEgABqQf//A3FBkIiAgABqLQAAciICOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMkQELQQAgAkEDajsBkIiEgABBAEEALQCSiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJSIhIAAakH//wNxQZCIgIAAai0AAHIiAjoAkoiEgABBACACQf8BcUVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADJABC0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgABBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGoiAkEBakH/AXFBkIiAgABqLQAAQQh0IAJB/wFxQZCIgIAAai0AAHJBkIiAgABqLQAAciICOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMjwELQQAgAkECajsBkIiEgABBAEEALQCSiISAACADQf//A3FBkIiAgABqLQAAIgJBAWpB/wFxQZCIgIAAai0AAEEIdCACQZCIgIAAai0AAHJBAC0AlIiEgABqQf//A3FBkIiAgABqLQAAciICOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMjgELQQAgAkECajsBkIiEgABBAEEALQCSiISAACADQf//A3FBkIiAgABqLQAAcSICOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMjQELQQAgAkECajsBkIiEgABBAEEALQCSiISAACADQf//A3FBkIiAgABqLQAAQZCIgIAAai0AAHEiAjoAkoiEgABBACACQf8BcUVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADIwBC0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgABBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGpB/wFxQZCIgIAAai0AAHEiAjoAkoiEgABBACACQf8BcUVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADIsBC0EAIAJBA2o7AZCIhIAAQQBBAC0AkoiEgAAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckGQiICAAGotAABxIgI6AJKIhIAAQQAgAkH/AXFFQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAyKAQtBACACQQNqOwGQiISAAEEAQQAtAJKIhIAAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0Ak4iEgABqQf//A3FBkIiAgABqLQAAcSICOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMiQELQQAgAkEDajsBkIiEgABBAEEALQCSiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJSIhIAAakH//wNxQZCIgIAAai0AAHEiAjoAkoiEgABBACACQf8BcUVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADIgBC0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgABBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGoiAkEBakH/AXFBkIiAgABqLQAAQQh0IAJB/wFxQZCIgIAAai0AAHJBkIiAgABqLQAAcSICOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMhwELQQAgAkECajsBkIiEgABBAEEALQCSiISAACADQf//A3FBkIiAgABqLQAAIgJBAWpB/wFxQZCIgIAAai0AAEEIdCACQZCIgIAAai0AAHJBAC0AlIiEgABqQf//A3FBkIiAgABqLQAAcSICOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMhgELQQAgAkECajsBkIiEgABBAEEALQCSiISAACICIANB//8DcUGQiICAAGotAAAiBHMiAzoAkoiEgABBACACIARGQQF0IANBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAyFAQtBACACQQJqOwGQiISAAEEAQQAtAJKIhIAAIgIgA0H//wNxQZCIgIAAai0AAEGQiICAAGotAAAiBHMiAzoAkoiEgABBACACIARGQQF0IANBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAyEAQtBACACQQJqOwGQiISAAEEAQQAtAJKIhIAAIgJBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGpB/wFxQZCIgIAAai0AACIEcyIDOgCSiISAAEEAIAIgBEZBAXQgA0GAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADIMBC0EAIAJBA2o7AZCIhIAAQQBBAC0AkoiEgAAiBCACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAai0AACICcyIDOgCSiISAAEEAIAQgAkZBAXQgA0GAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADIIBC0EAIAJBA2o7AZCIhIAAQQBBAC0AkoiEgAAiBCACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJOIhIAAakH//wNxQZCIgIAAai0AACICcyIDOgCSiISAAEEAIAQgAkZBAXQgA0GAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADIEBC0EAIAJBA2o7AZCIhIAAQQBBAC0AkoiEgAAiBCACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJSIhIAAakH//wNxQZCIgIAAai0AACICcyIDOgCSiISAAEEAIAQgAkZBAXQgA0GAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADIABC0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgAAiAkEALQCTiISAACADQf//A3FBkIiAgABqLQAAaiIEQQFqQf8BcUGQiICAAGotAABBCHQgBEH/AXFBkIiAgABqLQAAckGQiICAAGotAAAiBHMiAzoAkoiEgABBACACIARGQQF0IANBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAx/C0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgAAiAiADQf//A3FBkIiAgABqLQAAIgRBAWpB/wFxQZCIgIAAai0AAEEIdCAEQZCIgIAAai0AAHJBAC0AlIiEgABqQf//A3FBkIiAgABqLQAAIgRzIgM6AJKIhIAAQQAgAiAERkEBdCADQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMfgtBACACQQJqOwGQiISAAEEALQCSiISAACICIANB//8DcUGQiICAAGotAAAiA2pBAC0AloiEgAAiBUEBcSIGaiIEIAJzIAMgAnNBf3NxQQF2QcAAcSAFQb8BcXIhBwJAAkAgBUEIcUUNACACQQ9xIANBD3FqIAZqIgVBCUsiBiACQQR2IANBBHZqaiICQQZqIAIgAkEJSxsiA0EEdCAFQQZqIAUgBhtBD3FyIQIgB0H8AHEgA0EPS3IhAwwBCyAHQQFyIAdB9ABxIARB/wFLG0H1AHEhAyAEIQILQQAgAjoAkoiEgABBACAEQf8BcUVBAXQgBEGAAXFyIANyOgCWiISAAAx9C0EAIAJBAmo7AZCIhIAAQQAtAJKIhIAAIgIgA0H//wNxQZCIgIAAai0AAEGQiICAAGotAAAiA2pBAC0AloiEgAAiBUEBcSIGaiIEIAJzIAMgAnNBf3NxQQF2QcAAcSAFQb8BcXIhBwJAAkAgBUEIcUUNACACQQ9xIANBD3FqIAZqIgVBCUsiBiACQQR2IANBBHZqaiICQQZqIAIgAkEJSxsiA0EEdCAFQQZqIAUgBhtBD3FyIQIgB0H8AHEgA0EPS3IhAwwBCyAHQQFyIAdB9ABxIARB/wFLG0H1AHEhAyAEIQILQQAgAjoAkoiEgABBACAEQf8BcUVBAXQgBEGAAXFyIANyOgCWiISAAAx8C0EAIAJBAmo7AZCIhIAAQQAtAJKIhIAAIgJBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGpB/wFxQZCIgIAAai0AACIDakEALQCWiISAACIFQQFxIgZqIgQgAnMgAyACc0F/c3FBAXZBwABxIAVBvwFxciEHAkACQCAFQQhxRQ0AIAJBD3EgA0EPcWogBmoiBUEJSyIGIAJBBHYgA0EEdmpqIgJBBmogAiACQQlLGyIDQQR0IAVBBmogBSAGG0EPcXIhAiAHQfwAcSADQQ9LciEDDAELIAdBAXIgB0H0AHEgBEH/AUsbQfUAcSEDIAQhAgtBACACOgCSiISAAEEAIARB/wFxRUEBdCAEQYABcXIgA3I6AJaIhIAADHsLQQAgAkEDajsBkIiEgABBAC0AkoiEgAAiBCACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAai0AACIDakEALQCWiISAACIFQQFxIgZqIgIgBHMgAyAEc0F/c3FBAXZBwABxIAVBvwFxciEHAkACQCAFQQhxRQ0AIARBD3EgA0EPcWogBmoiBUEJSyIGIARBBHYgA0EEdmpqIgRBBmogBCAEQQlLGyIDQQR0IAVBBmogBSAGG0EPcXIhBCAHQfwAcSADQQ9LciEDDAELIAdBAXIgB0H0AHEgAkH/AUsbQfUAcSEDIAIhBAtBACAEOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXIgA3I6AJaIhIAADHoLQQAgAkEDajsBkIiEgABBAC0AkoiEgAAiBCACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJOIhIAAakH//wNxQZCIgIAAai0AACIDakEALQCWiISAACIFQQFxIgZqIgIgBHMgAyAEc0F/c3FBAXZBwABxIAVBvwFxciEHAkACQCAFQQhxRQ0AIARBD3EgA0EPcWogBmoiBUEJSyIGIARBBHYgA0EEdmpqIgRBBmogBCAEQQlLGyIDQQR0IAVBBmogBSAGG0EPcXIhBCAHQfwAcSADQQ9LciEDDAELIAdBAXIgB0H0AHEgAkH/AUsbQfUAcSEDIAIhBAtBACAEOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXIgA3I6AJaIhIAADHkLQQAgAkEDajsBkIiEgABBAC0AkoiEgAAiBCACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJSIhIAAakH//wNxQZCIgIAAai0AACIDakEALQCWiISAACIFQQFxIgZqIgIgBHMgAyAEc0F/c3FBAXZBwABxIAVBvwFxciEHAkACQCAFQQhxRQ0AIARBD3EgA0EPcWogBmoiBUEJSyIGIARBBHYgA0EEdmpqIgRBBmogBCAEQQlLGyIDQQR0IAVBBmogBSAGG0EPcXIhBCAHQfwAcSADQQ9LciEDDAELIAdBAXIgB0H0AHEgAkH/AUsbQfUAcSEDIAIhBAtBACAEOgCSiISAAEEAIAJB/wFxRUEBdCACQYABcXIgA3I6AJaIhIAADHgLQQAgAkECajsBkIiEgABBAC0AkoiEgAAiAkEALQCTiISAACADQf//A3FBkIiAgABqLQAAaiIEQQFqQf8BcUGQiICAAGotAABBCHQgBEH/AXFBkIiAgABqLQAAckGQiICAAGotAAAiA2pBAC0AloiEgAAiBUEBcSIGaiIEIAJzIAMgAnNBf3NxQQF2QcAAcSAFQb8BcXIhBwJAAkAgBUEIcUUNACACQQ9xIANBD3FqIAZqIgVBCUsiBiACQQR2IANBBHZqaiICQQZqIAIgAkEJSxsiA0EEdCAFQQZqIAUgBhtBD3FyIQIgB0H8AHEgA0EPS3IhAwwBCyAHQQFyIAdB9ABxIARB/wFLG0H1AHEhAyAEIQILQQAgAjoAkoiEgABBACAEQf8BcUVBAXQgBEGAAXFyIANyOgCWiISAAAx3C0EAIAJBAmo7AZCIhIAAQQAtAJKIhIAAIgIgA0H//wNxQZCIgIAAai0AACIEQQFqQf8BcUGQiICAAGotAABBCHQgBEGQiICAAGotAAByQQAtAJSIhIAAakH//wNxQZCIgIAAai0AACIDakEALQCWiISAACIFQQFxIgZqIgQgAnMgAyACc0F/c3FBAXZBwABxIAVBvwFxciEHAkACQCAFQQhxRQ0AIAJBD3EgA0EPcWogBmoiBUEJSyIGIAJBBHYgA0EEdmpqIgJBBmogAiACQQlLGyIDQQR0IAVBBmogBSAGG0EPcXIhAiAHQfwAcSADQQ9LciEDDAELIAdBAXIgB0H0AHEgBEH/AUsbQfUAcSEDIAQhAgtBACACOgCSiISAAEEAIARB/wFxRUEBdCAEQYABcXIgA3I6AJaIhIAADHYLQQAgAkECajsBkIiEgABBAC0AkoiEgAAiBCADQf//A3FBkIiAgABqLQAAIgVBAC0AloiEgAAiA0F/c0EBcSIGamsiAiAEcyAEIAVzcUH/AEtBBnQgA0G/AXFyIQcCQAJAIANBCHFFDQAgBEEPcSAGIAVBD3FqayIDQQ91IARBBHYgBUEEdmtqIgRBBHQiBUGgf2ogBSAEQQBIGyADQQpqIAMgA0EASBtBD3FyIQQgAkGAf3EgAkGAAklyIAJB/wFxRUEBdHIgB0H8AHFyIQMMAQsgAkH/AXFFQQF0IAJBgH9xciAHQQFyIAdB9ABxIAJBgAJJG0H1AHFyIQMgAiEEC0EAIAM6AJaIhIAAQQAgBDoAkoiEgAAMdQtBACACQQJqOwGQiISAAEEALQCSiISAACIEIANB//8DcUGQiICAAGotAABBkIiAgABqLQAAIgVBAC0AloiEgAAiA0F/c0EBcSIGamsiAiAEcyAEIAVzcUH/AEtBBnQgA0G/AXFyIQcCQAJAIANBCHFFDQAgBEEPcSAGIAVBD3FqayIDQQ91IARBBHYgBUEEdmtqIgRBBHQiBUGgf2ogBSAEQQBIGyADQQpqIAMgA0EASBtBD3FyIQQgAkGAf3EgAkGAAklyIAJB/wFxRUEBdHIgB0H8AHFyIQMMAQsgAkH/AXFFQQF0IAJBgH9xciAHQQFyIAdB9ABxIAJBgAJJG0H1AHFyIQMgAiEEC0EAIAM6AJaIhIAAQQAgBDoAkoiEgAAMdAtBACACQQJqOwGQiISAAEEALQCSiISAACIEQQAtAJOIhIAAIANB//8DcUGQiICAAGotAABqQf8BcUGQiICAAGotAAAiBUEALQCWiISAACIDQX9zQQFxIgZqayICIARzIAQgBXNxQf8AS0EGdCADQb8BcXIhBwJAAkAgA0EIcUUNACAEQQ9xIAYgBUEPcWprIgNBD3UgBEEEdiAFQQR2a2oiBEEEdCIFQaB/aiAFIARBAEgbIANBCmogAyADQQBIG0EPcXIhBCACQYB/cSACQYACSXIgAkH/AXFFQQF0ciAHQfwAcXIhAwwBCyACQf8BcUVBAXQgAkGAf3FyIAdBAXIgB0H0AHEgAkGAAkkbQfUAcXIhAyACIQQLQQAgAzoAloiEgABBACAEOgCSiISAAAxzC0EAIAJBA2o7AZCIhIAAQQAtAJKIhIAAIgQgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckGQiICAAGotAAAiBUEALQCWiISAACIDQX9zQQFxIgZqayICIARzIAQgBXNxQf8AS0EGdCADQb8BcXIhBwJAAkAgA0EIcUUNACAEQQ9xIAYgBUEPcWprIgNBD3UgBEEEdiAFQQR2a2oiBEEEdCIFQaB/aiAFIARBAEgbIANBCmogAyADQQBIG0EPcXIhBCACQYB/cSACQYACSXIgAkH/AXFFQQF0ciAHQfwAcXIhAwwBCyACQf8BcUVBAXQgAkGAf3FyIAdBAXIgB0H0AHEgAkGAAkkbQfUAcXIhAyACIQQLQQAgAzoAloiEgABBACAEOgCSiISAAAxyC0EAIAJBA2o7AZCIhIAAQQAtAJKIhIAAIgQgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckEALQCTiISAAGpB//8DcUGQiICAAGotAAAiBUEALQCWiISAACIDQX9zQQFxIgZqayICIARzIAQgBXNxQf8AS0EGdCADQb8BcXIhBwJAAkAgA0EIcUUNACAEQQ9xIAYgBUEPcWprIgNBD3UgBEEEdiAFQQR2a2oiBEEEdCIFQaB/aiAFIARBAEgbIANBCmogAyADQQBIG0EPcXIhBCACQYB/cSACQYACSXIgAkH/AXFFQQF0ciAHQfwAcXIhAwwBCyACQf8BcUVBAXQgAkGAf3FyIAdBAXIgB0H0AHEgAkGAAkkbQfUAcXIhAyACIQQLQQAgAzoAloiEgABBACAEOgCSiISAAAxxC0EAIAJBA2o7AZCIhIAAQQAtAJKIhIAAIgQgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckEALQCUiISAAGpB//8DcUGQiICAAGotAAAiBUEALQCWiISAACIDQX9zQQFxIgZqayICIARzIAQgBXNxQf8AS0EGdCADQb8BcXIhBwJAAkAgA0EIcUUNACAEQQ9xIAYgBUEPcWprIgNBD3UgBEEEdiAFQQR2a2oiBEEEdCIFQaB/aiAFIARBAEgbIANBCmogAyADQQBIG0EPcXIhBCACQYB/cSACQYACSXIgAkH/AXFFQQF0ciAHQfwAcXIhAwwBCyACQf8BcUVBAXQgAkGAf3FyIAdBAXIgB0H0AHEgAkGAAkkbQfUAcXIhAyACIQQLQQAgAzoAloiEgABBACAEOgCSiISAAAxwC0EAIAJBAmo7AZCIhIAAQQAtAJKIhIAAIgRBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGoiAkEBakH/AXFBkIiAgABqLQAAQQh0IAJB/wFxQZCIgIAAai0AAHJBkIiAgABqLQAAIgVBAC0AloiEgAAiA0F/c0EBcSIGamsiAiAEcyAEIAVzcUH/AEtBBnQgA0G/AXFyIQcCQAJAIANBCHFFDQAgBEEPcSAGIAVBD3FqayIDQQ91IARBBHYgBUEEdmtqIgRBBHQiBUGgf2ogBSAEQQBIGyADQQpqIAMgA0EASBtBD3FyIQQgAkGAf3EgAkGAAklyIAJB/wFxRUEBdHIgB0H8AHFyIQMMAQsgAkH/AXFFQQF0IAJBgH9xciAHQQFyIAdB9ABxIAJBgAJJG0H1AHFyIQMgAiEEC0EAIAM6AJaIhIAAQQAgBDoAkoiEgAAMbwtBACACQQJqOwGQiISAAEEALQCSiISAACIEIANB//8DcUGQiICAAGotAAAiAkEBakH/AXFBkIiAgABqLQAAQQh0IAJBkIiAgABqLQAAckEALQCUiISAAGpB//8DcUGQiICAAGotAAAiBUEALQCWiISAACIDQX9zQQFxIgZqayICIARzIAQgBXNxQf8AS0EGdCADQb8BcXIhBwJAAkAgA0EIcUUNACAEQQ9xIAYgBUEPcWprIgNBD3UgBEEEdiAFQQR2a2oiBEEEdCIFQaB/aiAFIARBAEgbIANBCmogAyADQQBIG0EPcXIhBCACQYB/cSACQYACSXIgAkH/AXFFQQF0ciAHQfwAcXIhAwwBCyACQf8BcUVBAXQgAkGAf3FyIAdBAXIgB0H0AHEgAkGAAkkbQfUAcXIhAyACIQQLQQAgAzoAloiEgABBACAEOgCSiISAAAxuC0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgAAiAiADQf//A3FBkIiAgABqLQAAIgRGQQF0IAIgBGtBgAFxciACIARPckEALQCWiISAAEH8AHFyOgCWiISAAAxtC0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgAAiAiADQf//A3FBkIiAgABqLQAAQZCIgIAAai0AACIERkEBdCACIARrQYABcXIgAiAET3JBAC0AloiEgABB/ABxcjoAloiEgAAMbAtBACACQQJqOwGQiISAAEEAQQAtAJKIhIAAIgJBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGpB/wFxQZCIgIAAai0AACIERkEBdCACIARrQYABcXIgAiAET3JBAC0AloiEgABB/ABxcjoAloiEgAAMawtBACACQQNqOwGQiISAAEEAQQAtAJKIhIAAIgQgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckGQiICAAGotAAAiAkZBAXQgBCACa0GAAXFyIAQgAk9yQQAtAJaIhIAAQfwAcXI6AJaIhIAADGoLQQAgAkEDajsBkIiEgABBAEEALQCSiISAACIEIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0Ak4iEgABqQf//A3FBkIiAgABqLQAAIgJGQQF0IAQgAmtBgAFxciAEIAJPckEALQCWiISAAEH8AHFyOgCWiISAAAxpC0EAIAJBA2o7AZCIhIAAQQBBAC0AkoiEgAAiBCACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJSIhIAAakH//wNxQZCIgIAAai0AACICRkEBdCAEIAJrQYABcXIgBCACT3JBAC0AloiEgABB/ABxcjoAloiEgAAMaAtBACACQQJqOwGQiISAAEEAQQAtAJKIhIAAIgJBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGoiBEEBakH/AXFBkIiAgABqLQAAQQh0IARB/wFxQZCIgIAAai0AAHJBkIiAgABqLQAAIgRGQQF0IAIgBGtBgAFxciACIARPckEALQCWiISAAEH8AHFyOgCWiISAAAxnC0EAIAJBAmo7AZCIhIAAQQBBAC0AkoiEgAAiAiADQf//A3FBkIiAgABqLQAAIgRBAWpB/wFxQZCIgIAAai0AAEEIdCAEQZCIgIAAai0AAHJBAC0AlIiEgABqQf//A3FBkIiAgABqLQAAIgRGQQF0IAIgBGtBgAFxciACIARPckEALQCWiISAAEH8AHFyOgCWiISAAAxmC0EAIAJBAmo7AZCIhIAAQQBBAC0Ak4iEgAAiAiADQf//A3FBkIiAgABqLQAAIgRGQQF0IAIgBGtBgAFxciACIARPckEALQCWiISAAEH8AHFyOgCWiISAAAxlC0EAIAJBAmo7AZCIhIAAQQBBAC0Ak4iEgAAiAiADQf//A3FBkIiAgABqLQAAQZCIgIAAai0AACIERkEBdCACIARrQYABcXIgAiAET3JBAC0AloiEgABB/ABxcjoAloiEgAAMZAtBACACQQNqOwGQiISAAEEAQQAtAJOIhIAAIgQgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckGQiICAAGotAAAiAkZBAXQgBCACa0GAAXFyIAQgAk9yQQAtAJaIhIAAQfwAcXI6AJaIhIAADGMLQQAgAkECajsBkIiEgABBAEEALQCUiISAACICIANB//8DcUGQiICAAGotAAAiBEZBAXQgAiAEa0GAAXFyIAIgBE9yQQAtAJaIhIAAQfwAcXI6AJaIhIAADGILQQAgAkECajsBkIiEgABBAEEALQCUiISAACICIANB//8DcUGQiICAAGotAABBkIiAgABqLQAAIgRGQQF0IAIgBGtBgAFxciACIARPckEALQCWiISAAEH8AHFyOgCWiISAAAxhC0EAIAJBA2o7AZCIhIAAQQBBAC0AlIiEgAAiBCACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAai0AACICRkEBdCAEIAJrQYABcXIgBCACT3JBAC0AloiEgABB/ABxcjoAloiEgAAMYAtBACACQQJqOwGQiISAAEEAIANB//8DcUGQiICAAGotAAAiAjoAkoiEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMXwtBACACQQJqOwGQiISAAEEAIANB//8DcUGQiICAAGotAABBkIiAgABqLQAAIgI6AJKIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADF4LQQAgAkECajsBkIiEgABBAEEALQCTiISAACADQf//A3FBkIiAgABqLQAAakH/AXFBkIiAgABqLQAAIgI6AJKIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADF0LQQAgAkEDajsBkIiEgABBACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAai0AACICOgCSiISAAEEAIAJFQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAxcC0EAIAJBA2o7AZCIhIAAQQAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckEALQCTiISAAGpB//8DcUGQiICAAGotAAAiAjoAkoiEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMWwtBACACQQNqOwGQiISAAEEAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0AlIiEgABqQf//A3FBkIiAgABqLQAAIgI6AJKIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADFoLQQAgAkECajsBkIiEgABBAEEALQCTiISAACADQf//A3FBkIiAgABqLQAAaiICQQFqQf8BcUGQiICAAGotAABBCHQgAkH/AXFBkIiAgABqLQAAckGQiICAAGotAAAiAjoAkoiEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMWQtBACACQQJqOwGQiISAAEEAIANB//8DcUGQiICAAGotAAAiAkEBakH/AXFBkIiAgABqLQAAQQh0IAJBkIiAgABqLQAAckEALQCUiISAAGpB//8DcUGQiICAAGotAAAiAjoAkoiEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMWAtBACACQQJqOwGQiISAAEEAIANB//8DcUGQiICAAGotAAAiAjoAk4iEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMVwtBACACQQJqOwGQiISAAEEAIANB//8DcUGQiICAAGotAABBkIiAgABqLQAAIgI6AJOIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADFYLQQAgAkECajsBkIiEgABBAEEALQCUiISAACADQf//A3FBkIiAgABqLQAAakH/AXFBkIiAgABqLQAAIgI6AJOIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADFULQQAgAkEDajsBkIiEgABBACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAai0AACICOgCTiISAAEEAIAJFQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAxUC0EAIAJBA2o7AZCIhIAAQQAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckEALQCUiISAAGpB//8DcUGQiICAAGotAAAiAjoAk4iEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMUwtBACACQQJqOwGQiISAAEEAIANB//8DcUGQiICAAGotAAAiAjoAlIiEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMUgtBACACQQJqOwGQiISAAEEAIANB//8DcUGQiICAAGotAABBkIiAgABqLQAAIgI6AJSIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADFELQQAgAkECajsBkIiEgABBAEEALQCTiISAACADQf//A3FBkIiAgABqLQAAakH/AXFBkIiAgABqLQAAIgI6AJSIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADFALQQAgAkEDajsBkIiEgABBACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAai0AACICOgCUiISAAEEAIAJFQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAxPC0EAIAJBA2o7AZCIhIAAQQAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckEALQCTiISAAGpB//8DcUGQiICAAGotAAAiAjoAlIiEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMTgtBACACQQJqOwGQiISAACADQf//A3FBkIiAgABqLQAAQZCIgIAAakEALQCSiISAADoAAAxNC0EAIAJBAmo7AZCIhIAAQQAtAJOIhIAAIANB//8DcUGQiICAAGotAABqQf8BcUGQiICAAGpBAC0AkoiEgAA6AAAMTAtBACACQQNqOwGQiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAakEALQCSiISAADoAAAxLC0EAIAJBA2o7AZCIhIAAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0Ak4iEgABqQf//A3FBkIiAgABqQQAtAJKIhIAAOgAADEoLQQAgAkEDajsBkIiEgAAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckEALQCUiISAAGpB//8DcUGQiICAAGpBAC0AkoiEgAA6AAAMSQtBACACQQJqOwGQiISAAEEALQCTiISAACADQf//A3FBkIiAgABqLQAAaiICQQFqQf8BcUGQiICAAGotAABBCHQgAkH/AXFBkIiAgABqLQAAckGQiICAAGpBAC0AkoiEgAA6AAAMSAtBACACQQJqOwGQiISAACADQf//A3FBkIiAgABqLQAAIgJBAWpB/wFxQZCIgIAAai0AAEEIdCACQZCIgIAAai0AAHJBAC0AlIiEgABqQf//A3FBkIiAgABqQQAtAJKIhIAAOgAADEcLQQAgAkECajsBkIiEgAAgA0H//wNxQZCIgIAAai0AAEGQiICAAGpBAC0Ak4iEgAA6AAAMRgtBACACQQJqOwGQiISAAEEALQCUiISAACADQf//A3FBkIiAgABqLQAAakH/AXFBkIiAgABqQQAtAJOIhIAAOgAADEULQQAgAkEDajsBkIiEgAAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckGQiICAAGpBAC0Ak4iEgAA6AAAMRAtBACACQQJqOwGQiISAACADQf//A3FBkIiAgABqLQAAQZCIgIAAakEALQCUiISAADoAAAxDC0EAIAJBAmo7AZCIhIAAQQAtAJOIhIAAIANB//8DcUGQiICAAGotAABqQf8BcUGQiICAAGpBAC0AlIiEgAA6AAAMQgtBACACQQNqOwGQiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAakEALQCUiISAADoAAAxBC0EAQQAtAJKIhIAAIgI6AJOIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADEALQQBBAC0Ak4iEgAAiAjoAkoiEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMPwtBAEEALQCSiISAACICOgCUiISAAEEAIAJFQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAw+C0EAQQAtAJSIhIAAIgI6AJKIhIAAQQAgAkVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADD0LQQBBAC0AlYiEgAAiAjoAk4iEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMPAtBAEEALQCTiISAADoAlYiEgAAMOwtBACACQQJqOwGQiISAACADQf//A3FBkIiAgABqLQAAQZCIgIAAaiICIAItAABBAWoiAjoAAEEAIAJB/wFxIAJHQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAw6C0EAIAJBAmo7AZCIhIAAQQAtAJOIhIAAIANB//8DcUGQiICAAGotAABqQf8BcUGQiICAAGoiAiACLQAAQQFqIgI6AABBACACQf8BcSACR0EBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMOQtBACACQQNqOwGQiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAaiICIAItAABBAWoiAjoAAEEAIAJB/wFxIAJHQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAw4C0EAIAJBA2o7AZCIhIAAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0Ak4iEgABqQf//A3FBkIiAgABqIgIgAi0AAEEBaiICOgAAQQAgAkH/AXEgAkdBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADDcLQQAgAkECajsBkIiEgAAgA0H//wNxQZCIgIAAai0AAEGQiICAAGoiAiACLQAAQX9qIgI6AABBACACQf8BcUVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADDYLQQAgAkECajsBkIiEgABBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGpB/wFxQZCIgIAAaiICIAItAABBf2oiAjoAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMNQtBACACQQNqOwGQiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAaiICIAItAABBf2oiAjoAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMNAtBACACQQNqOwGQiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJOIhIAAakH//wNxQZCIgIAAaiICIAItAABBf2oiAjoAAEEAIAJB/wFxRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMMwtBAEEALQCTiISAAEEBaiICOgCTiISAAEEAIAJB/wFxIAJHQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAwyC0EAQQAtAJOIhIAAQX9qIgI6AJOIhIAAQQAgAkH/AXFFQQF0IAJBgAFxckEALQCWiISAAEH9AHFyOgCWiISAAAwxC0EAQQAtAJSIhIAAQQFqIgI6AJSIhIAAQQAgAkH/AXEgAkdBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADDALQQBBAC0AlIiEgABBf2oiAjoAlIiEgABBACACQf8BcUVBAXQgAkGAAXFyQQAtAJaIhIAAQf0AcXI6AJaIhIAADC8LQQBBAC0AkoiEgAAiBEEBdCICOgCSiISAAEEAIAIgBEEHdnJBgQFxQQAtAJaIhIAAQfwAcXIgAkH+AXFFQQF0cjoAloiEgAAMLgtBACACQQJqOwGQiISAACADQf//A3FBkIiAgABqLQAAQZCIgIAAaiICIAItAAAiBEEBdCICOgAAQQAgAiAEQQd2ckGBAXFBAC0AloiEgABB/ABxciACQf4BcUVBAXRyOgCWiISAAAwtC0EAIAJBAmo7AZCIhIAAQQAtAJOIhIAAIANB//8DcUGQiICAAGotAABqQf8BcUGQiICAAGoiAiACLQAAIgRBAXQiAjoAAEEAIAIgBEEHdnJBgQFxQQAtAJaIhIAAQfwAcXIgAkH+AXFFQQF0cjoAloiEgAAMLAtBACACQQNqOwGQiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAaiICIAItAAAiBEEBdCICOgAAQQAgAiAEQQd2ckGBAXFBAC0AloiEgABB/ABxciACQf4BcUVBAXRyOgCWiISAAAwrC0EAIAJBA2o7AZCIhIAAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0Ak4iEgABqQf//A3FBkIiAgABqIgIgAi0AACIEQQF0IgI6AABBACACIARBB3ZyQYEBcUEALQCWiISAAEH8AHFyIAJB/gFxRUEBdHI6AJaIhIAADCoLQQBBAC0AkoiEgAAiAkEBdjoAkoiEgABBACACQQJJQQF0IAJBAXFyQQAtAJaIhIAAQfwAcXI6AJaIhIAADCkLQQAgAkECajsBkIiEgAAgA0H//wNxQZCIgIAAai0AAEGQiICAAGoiAiACLQAAIgJBAXY6AABBACACQQJJQQF0IAJBAXFyQQAtAJaIhIAAQfwAcXI6AJaIhIAADCgLQQAgAkECajsBkIiEgABBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGpB/wFxQZCIgIAAaiICIAItAAAiAkEBdjoAAEEAIAJBAklBAXQgAkEBcXJBAC0AloiEgABB/ABxcjoAloiEgAAMJwtBACACQQNqOwGQiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQZCIgIAAaiICIAItAAAiAkEBdjoAAEEAIAJBAklBAXQgAkEBcXJBAC0AloiEgABB/ABxcjoAloiEgAAMJgtBACACQQNqOwGQiISAACACQQJqQf//A3FBkIiAgABqLQAAQQh0IANB//8DcUGQiICAAGotAAByQQAtAJOIhIAAakH//wNxQZCIgIAAaiICIAItAAAiAkEBdjoAAEEAIAJBAklBAXQgAkEBcXJBAC0AloiEgABB/ABxcjoAloiEgAAMJQtBAEEALQCWiISAACICQQFxQQAtAJKIhIAAIgRBAXQiA3IiBToAkoiEgABBACADIARBB3ZyQYEBcSACQfwAcXIgBUH/AXFFQQF0cjoAloiEgAAMJAtBACACQQJqOwGQiISAACADQf//A3FBkIiAgABqLQAAQZCIgIAAaiICQQAtAJaIhIAAIgRBAXEgAi0AACICQQF0IgNyIgU6AABBACADIAJBB3ZyQYEBcSAEQfwAcXIgBUH/AXFFQQF0cjoAloiEgAAMIwtBACACQQJqOwGQiISAAEEALQCTiISAACADQf//A3FBkIiAgABqLQAAakH/AXFBkIiAgABqIgJBAC0AloiEgAAiBEEBcSACLQAAIgJBAXQiA3IiBToAAEEAIAMgAkEHdnJBgQFxIARB/ABxciAFQf8BcUVBAXRyOgCWiISAAAwiC0EAIAJBA2o7AZCIhIAAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBkIiAgABqIgJBAC0AloiEgAAiBEEBcSACLQAAIgJBAXQiA3IiBToAAEEAIAMgAkEHdnJBgQFxIARB/ABxciAFQf8BcUVBAXRyOgCWiISAAAwhC0EAIAJBA2o7AZCIhIAAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0Ak4iEgABqQf//A3FBkIiAgABqIgJBAC0AloiEgAAiBEEBcSACLQAAIgJBAXQiA3IiBToAAEEAIAMgAkEHdnJBgQFxIARB/ABxciAFQf8BcUVBAXRyOgCWiISAAAwgC0EAQQAtAJaIhIAAIgRBB3RBAC0AkoiEgAAiA0EBdnIiAjoAkoiEgABBACAEQfwAcSADQQFxciACQYABcXIgAkH/AXFFQQF0cjoAloiEgAAMHwtBACACQQJqOwGQiISAACADQf//A3FBkIiAgABqLQAAQZCIgIAAaiICQQAtAJaIhIAAIgRBB3QgAi0AACIDQQF2ciICOgAAQQAgBEH8AHEgA0EBcXIgAkGAAXFyIAJB/wFxRUEBdHI6AJaIhIAADB4LQQAgAkECajsBkIiEgABBAC0Ak4iEgAAgA0H//wNxQZCIgIAAai0AAGpB/wFxQZCIgIAAaiICQQAtAJaIhIAAIgRBB3QgAi0AACIDQQF2ciICOgAAQQAgBEH8AHEgA0EBcXIgAkGAAXFyIAJB/wFxRUEBdHI6AJaIhIAADB0LQQAgAkEDajsBkIiEgAAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckGQiICAAGoiAkEALQCWiISAACIEQQd0IAItAAAiA0EBdnIiAjoAAEEAIARB/ABxIANBAXFyIAJBgAFxciACQf8BcUVBAXRyOgCWiISAAAwcC0EAIAJBA2o7AZCIhIAAIAJBAmpB//8DcUGQiICAAGotAABBCHQgA0H//wNxQZCIgIAAai0AAHJBAC0Ak4iEgABqQf//A3FBkIiAgABqIgJBAC0AloiEgAAiBEEHdCACLQAAIgNBAXZyIgI6AABBACAEQfwAcSADQQFxciACQYABcXIgAkH/AXFFQQF0cjoAloiEgAAMGwtBACACQQJqOwGQiISAAEEAQQAtAJaIhIAAQT1xIANB//8DcUGQiICAAGotAABBkIiAgABqLQAAIgJBwAFxckEALQCSiISAACACcUVBAXRyOgCWiISAAAwaC0EAIAJBA2o7AZCIhIAAQQBBAC0AloiEgABBPXEgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAckGQiICAAGotAAAiAkHAAXFyQQAtAJKIhIAAIAJxRUEBdHI6AJaIhIAADBkLQQAgAkECaiICOwGQiISAAEEALACWiISAAEEASA0YQQAgAiADQf//A3FBkIiAgABqLAAAajsBkIiEgAAMGAtBACACQQJqIgI7AZCIhIAAQQAsAJaIhIAAQX9KDRdBACACIANB//8DcUGQiICAAGosAABqOwGQiISAAAwXC0EAIAJBAmoiAjsBkIiEgABBAC0AloiEgABBwABxDRZBACACIANB//8DcUGQiICAAGosAABqOwGQiISAAAwWC0EAIAJBAmoiAjsBkIiEgABBAC0AloiEgABBwABxRQ0VQQAgAiADQf//A3FBkIiAgABqLAAAajsBkIiEgAAMFQtBACACQQJqIgI7AZCIhIAAQQAtAJaIhIAAQQFxDRRBACACIANB//8DcUGQiICAAGosAABqOwGQiISAAAwUC0EAIAJBAmoiAjsBkIiEgABBAC0AloiEgABBAXFFDRNBACACIANB//8DcUGQiICAAGosAABqOwGQiISAAAwTC0EAIAJBAmoiAjsBkIiEgABBAC0AloiEgABBAnENEkEAIAIgA0H//wNxQZCIgIAAaiwAAGo7AZCIhIAADBILQQAgAkECaiICOwGQiISAAEEALQCWiISAAEECcUUNEUEAIAIgA0H//wNxQZCIgIAAaiwAAGo7AZCIhIAADBELQQAgAkECakH//wNxQZCIgIAAai0AAEEIdCADQf//A3FBkIiAgABqLQAAcjsBkIiEgAAMEAtBACACQQJqQf//A3FBkIiAgABqLQAAQQh0IgIgA0H//wNxQZCIgIAAai0AACIEQQFqQf8BcXJB//8DcUGQiICAAGotAABBCHQgAiAEckH//wNxQZCIgIAAai0AAHI7AZCIhIAADA8LQQBBAC0AlYiEgAAiBEF+ajoAlYiEgAAgA0H//wNxQZCIgIAAai0AACEDIAJBAmoiAkH//wNxQZCIgIAAai0AACEFIARBkIqAgABqIAJBCHY6AAAgBEF/akH/AXFBkIqAgABqIAI6AABBACADIAVBCHRyOwGQiISAAAwOC0EAQQAtAJWIhIAAIgJBAmoiBDoAlYiEgABBACAEQf8BcUGQioCAAGotAABBCHQgAkEBakH/AXFBkIqAgABqLQAAckEBajsBkIiEgAAMDQtBAEEALQCViISAACICQQNqIgQ6AJWIhIAAQQAgAkEBakH/AXFBkIqAgABqLQAAQc8BcUEgcjoAloiEgABBACAEQf8BcUGQioCAAGotAABBCHQgAkECakH/AXFBkIqAgABqLQAAcjsBkIiEgAAMDAtBAEEALwGOiISAADsBkIiEgABBAC0AlYiEgAAiBEGQioCAAGogAkECaiICQQh2OgAAQQBBAC0AloiEgAAiA0EEcjoAloiEgABBACAEQX1qOgCViISAACAEQX9qQf8BcUGQioCAAGogAjoAACAEQX5qQf8BcUGQioCAAGogA0EwcjoAAAwLC0EALQCViISAACICQZCKgIAAakEALQCSiISAADoAAEEAIAJBf2o6AJWIhIAADAoLQQBBAC0AlYiEgABBAWoiAjoAlYiEgABBACACQf8BcUGQioCAAGotAAAiAjoAkoiEgABBACACRUEBdCACQYABcXJBAC0AloiEgABB/QBxcjoAloiEgAAMCQtBAC0AlYiEgAAiAkGQioCAAGpBAC0AloiEgABBMHI6AABBACACQX9qOgCViISAAAwIC0EAQQAtAJWIhIAAQQFqIgI6AJWIhIAAQQAgAkH/AXFBkIqAgABqLQAAQc8BcUEgcjoAloiEgAAMBwtBAEEALQCWiISAAEH+AXE6AJaIhIAADAYLQQBBAC0AloiEgABBAXI6AJaIhIAADAULQQBBAC0AloiEgABB+wFxOgCWiISAAAwEC0EAQQAtAJaIhIAAQQRyOgCWiISAAAwDC0EAQQAtAJaIhIAAQb8BcToAloiEgAAMAgtBAEEALQCWiISAAEH3AXE6AJaIhIAADAELQQBBAC0AloiEgABBCHI6AJaIhIAAC0EAQQAtAJaIhIAAQSByOgCWiISAACAAIAFBAWoiAUcNAAtBACAANgKciISAAEEADwtBACABNgKciISAAEEDCwsKAQBBgAgLA2n/AQ==';
    const ACTIVITY_RECORD_BYTES=10;
    const ACTIVITY_GROUP_MARKER_ADR=0xFFFF;
    const INSTRLEN=new Uint8Array([
      2,2,2,1,2,2,2,2, 1,2,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,3,1,1,3,3,3,3,
        3,2,2,1,2,2,2,2, 1,2,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,3,1,1,3,3,3,3,

        1,2,2,1,2,2,2,2, 1,2,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,3,1,1,3,3,3,3,
        1,2,2,1,2,2,2,2, 1,2,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,3,1,1,3,3,3,3,

        2,2,2,1,2,2,2,2, 1,2,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,3,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,2,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,3,1,1,3,3,3,3,

        2,2,2,1,2,2,2,2, 1,2,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,3,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,2,1,1,3,3,3,3,
        2,2,2,1,2,2,2,2, 1,3,1,1,3,3,3,3
    ]);
    const ACTIVITY_MEMBER_TABLE=[
      {group:1,step:0,pc:0xFD1B},{group:1,step:1,pc:0xFD1D},{group:1,step:2,pc:0xFD21},{group:1,step:3,pc:0xFD24},
        {group:2,step:0,pc:0xFCAA},{group:2,step:1,pc:0xFCAC},
        {group:3,step:0,pc:0xFCA0},{group:3,step:1,pc:0xFCA2},{group:3,step:2,pc:0xFCA3},{group:3,step:3,pc:0xFCA5},
        {group:4,step:0,pc:0xF181},{group:4,step:1,pc:0xF183},{group:4,step:2,pc:0xF185},{group:4,step:3,pc:0xF187},
        {group:4,step:4,pc:0xF189},{group:4,step:5,pc:0xF18B},{group:4,step:6,pc:0xF18D},{group:4,step:7,pc:0xF18F},
        {group:4,step:8,pc:0xF191},{group:4,step:9,pc:0xF193},
        {group:5,step:0,pc:0xF152},{group:5,step:1,pc:0xF155},{group:5,step:2,pc:0xF157},{group:5,step:3,pc:0xF159},{group:5,step:4,pc:0xF15A},
        {group:6,step:0,pc:0xFB65},{group:6,step:1,pc:0xFB68},{group:6,step:2,pc:0xFB6B},{group:6,step:3,pc:0xFB6C},
        {group:7,step:0,pc:0xFACE},{group:7,step:1,pc:0xFACF},{group:7,step:2,pc:0xFAD0},{group:7,step:3,pc:0xFAC7},{group:7,step:4,pc:0xFAC9},{group:7,step:5,pc:0xFACC},
        {group:8,step:0,pc:0xFCAE},{group:8,step:1,pc:0xFCAF},{group:8,step:2,pc:0xFCB1},{group:8,step:3,pc:0xFCA9}
    ];

    function decodeWasmBase64(s)
    {
        var raw=atob(s),out=new Uint8Array(raw.length);
        for(var i=0;i<raw.length;i++) out[i]=raw.charCodeAt(i);
        return out;
    }

    const wasmModulePromise=WebAssembly.compile(decodeWasmBase64(WASM_BASE64));
    var wasmInstance=null, e=null, wr=null;

    var wrapper_id="wasmCpu_popup";
    var phase="idle";       // idle | armed | running | paused
    var stopRequested=false;
    var pauseRequested=false;
    var sessionInstructions=0;
    // Chunk size used by the currently executing WASM segment.
    // It is latched when Run/Resume starts, so editing the UI cannot alter
    // an in-flight run.  A new value is picked up after Pause -> Resume.
    var runChunkInstructions=50000000;
    var sourceImage=null;
    var lastActivityLog=null;
    var activityLogger=null;
    var loggerEnabled=false;
    var loggerArmed=false;
    var loggerActive=false;
    var loggerComplete=false;
    var loggerStart=null;
    var loggerStop=null;
    var loggedSinceYield=0;
    var dynamicEscape=null;
    var lastUiRefreshMs=0;
    var speedIndicatorBackup=null;
    var runElapsedMs=0;
    var runSegmentStartMs=null;
    var progressBaseValue=null;
    var progressBaseElapsedMs=0;
    var progressLastValue=null;

    function $(id) { return typeof(document)!="undefined" ? document.getElementById(id) : null; }
    function hex(v,n) { return "$"+(Number(v)>>>0).toString(16).toUpperCase().padStart(n,"0"); }
    function toHex(v,n) { return (Number(v)>>>0).toString(16).toUpperCase().padStart(n,"0"); }
    function nextTick() { return new Promise(function(resolve){ setTimeout(resolve,0); }); }

    function parseOptionalAddress(value)
    {
        var s=String(value==null?"":value).trim();
        if(!s) return null;
        s=s.replace(/^\$/,'').replace(/^0x/i,'');
        if(!/^[0-9a-f]{1,4}$/i.test(s)) throw new Error("Invalid 6502 address: "+value);
        return parseInt(s,16)&0xffff;
    }

    function parseByte(id,def)
    {
        var el=$(id),s=String(el?el.value:"").trim().replace(/^\$/,'').replace(/^0x/i,'');
        if(!s) return def&0xff;
        if(!/^[0-9a-f]{1,2}$/i.test(s)) throw new Error("Invalid byte in "+id+": "+(el?el.value:""));
        return parseInt(s,16)&0xff;
    }

    function parseWord(id,def)
    {
        var el=$(id),s=String(el?el.value:"").trim().replace(/^\$/,'').replace(/^0x/i,'');
        if(!s) return def&0xffff;
        if(!/^[0-9a-f]{1,4}$/i.test(s)) throw new Error("Invalid word in "+id+": "+(el?el.value:""));
        return parseInt(s,16)&0xffff;
    }

    function parsePositive(id,def)
    {
        var el=$(id),v=Number(el?el.value:def);
        if(!Number.isFinite(v)||v<1) return def;
        return Math.min(0xffffffff,Math.floor(v));
    }

    // Human-facing chunk configuration is expressed in millions of
    // instructions.  Keep cpu_run_chunk() itself in exact instruction units.
    function parseChunkInstructions()
    {
        var el=$("wasm_chunk"),millions=Number(el?el.value:50);
        if(!Number.isFinite(millions)||millions<=0) millions=50;
        return Math.min(0xffffffff,Math.max(1,Math.floor(millions*1000000)));
    }

    function updateUiFpsLabel()
    {
        var el=$("wasm_ui_fps");
        if(!el) return;
        var hz=typeof(_o)!="undefined"?Number(_o.EMU_DashboardRefresh_s):0;
        el.textContent=(Number.isFinite(hz)&&hz>0?hz:2)+" fps";
    }

    function parseLimit()
    {
        var el=$("wasm_limit"),v=Number(el?el.value:0);
        return Number.isFinite(v)&&v>0?Math.floor(v):0;
    }

    function setStatus(text,cls)
    {
        var el=$("wasm_status");
        if(!el) return;
        el.textContent=text;
        el.style.color=cls==="bad"?"#B00020":(cls==="good"?"#006000":"#202020");
    }

    function setCurrentFields(state)
    {
        if(!state) return;
        var vals={pc:[state.pc,4],a:[state.a,2],x:[state.x,2],y:[state.y,2],sp:[state.sp,2],p:[state.p,2]};
        Object.keys(vals).forEach(function(k){ var el=$("wasm_cur_"+k); if(el) el.value=toHex(vals[k][0],vals[k][1]); });
    }

    // The normal dashboard and Disk II surface-map monitor use
    // _o.EMU_DashboardRefresh_s. The JavaScript CPU is paused during a WASM
    // handoff, so its RefreshEvent dispatcher is not ticking; use the same
    // configured wall-clock cadence here rather than updating the DOM after
    // every WASM chunk.
    function uiRefreshIntervalMs()
    {
        var hz=typeof(_o)!="undefined"?Number(_o.EMU_DashboardRefresh_s):0;
        return Number.isFinite(hz)&&hz>0?1000/hz:500;
    }

    function formatHMS(ms)
    {
        var total=Math.max(0,Math.floor((Number(ms)||0)/1000));
        var h=Math.floor(total/3600);
        var m=Math.floor((total%3600)/60);
        var s=total%60;
        return String(h).padStart(2,"0")+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0");
    }

    function currentRunElapsedMs()
    {
        var elapsed=runElapsedMs;
        if(runSegmentStartMs!==null)
            elapsed+=Math.max(0,performance.now()-runSegmentStartMs);
        return elapsed;
    }

    function updateElapsedTimer()
    {
        var el=$("wasm_elapsed");
        if(el) el.textContent=formatHMS(currentRunElapsedMs());
    }

    function startRunTimer()
    {
        if(runSegmentStartMs===null) runSegmentStartMs=performance.now();
        updateElapsedTimer();
    }

    function pauseRunTimer()
    {
        if(runSegmentStartMs!==null)
        {
            runElapsedMs+=Math.max(0,performance.now()-runSegmentStartMs);
            runSegmentStartMs=null;
        }
        updateElapsedTimer();
    }

    function resetRunTimer()
    {
        runElapsedMs=0;
        runSegmentStartMs=null;
        progressBaseValue=null;
        progressBaseElapsedMs=0;
        progressLastValue=null;
        updateElapsedTimer();
        var eta=$("wasm_eta");
        if(eta) eta.textContent="ETA --:--:--";
    }

    function resetProgressEstimate()
    {
        progressBaseValue=null;
        progressLastValue=null;
        progressBaseElapsedMs=currentRunElapsedMs();
        try
        {
            var addr=progressAddressFromUI();
            if(addr!==null&&wr) progressBaseValue=wr[addr]&0xff;
        }
        catch(err) {}
    }

    function estimateProgressEtaMs(value)
    {
        value=Number(value)&0xff;
        if(value>=255) return 0;
        if(progressBaseValue===null) return null;

        // If the monitored byte moved backwards, treat it as a new progress
        // epoch instead of producing a nonsensical negative ETA.
        if(value<progressBaseValue)
        {
            progressBaseValue=value;
            progressBaseElapsedMs=currentRunElapsedMs();
            return null;
        }

        var advanced=value-progressBaseValue;
        var elapsed=currentRunElapsedMs()-progressBaseElapsedMs;
        if(advanced<=0||elapsed<=0) return null;

        var unitsPerMs=advanced/elapsed;
        return unitsPerMs>0 ? (255-value)/unitsPerMs : null;
    }

    function progressAddressFromUI()
    {
        var el=$("wasm_progress_addr");
        return parseOptionalAddress(el?el.value:"");
    }

    function updateProgressMonitor()
    {
        var bar=$("wasm_progress_bar"),text=$("wasm_progress_text"),eta=$("wasm_eta");
        if(!bar&&!text&&!eta) return;

        var addr=null;
        try { addr=progressAddressFromUI(); }
        catch(err)
        {
            if(bar) bar.value=0;
            if(text) text.textContent="invalid address";
            if(eta) eta.textContent="ETA --:--:--";
            progressLastValue=null;
            return;
        }

        if(addr===null||!wr)
        {
            if(bar) bar.value=0;
            if(text) text.textContent="--.-%";
            if(eta) eta.textContent="ETA --:--:--";
            progressLastValue=null;
            return;
        }

        var value=wr[addr]&0xff;
        var pct=Math.round(value*1000/255)/10;
        if(bar)
        {
            bar.max=255;
            bar.value=value;
            bar.title=hex(addr,4)+" = "+toHex(value,2)+" ("+pct.toFixed(1)+"%)";
        }
        if(text) text.textContent=pct.toFixed(1)+"%";
        // ETA is derived from observed progress, not from the UI refresh
        // cadence.  Keep the previous estimate unchanged until this byte
        // actually changes.
        if(eta)
        {
            if(progressLastValue===null)
            {
                progressLastValue=value;
                eta.textContent=value>=255 ? "ETA 00:00:00" : "ETA --:--:--";
            }
            else if(value!==progressLastValue)
            {
                progressLastValue=value;
                var etaMs=estimateProgressEtaMs(value);
                eta.textContent="ETA "+(etaMs===null?"--:--:--":formatHMS(etaMs));
            }
        }
    }

    function refreshWasmUi(force)
    {
        var now=performance.now();
        if(!force && now-lastUiRefreshMs<uiRefreshIntervalMs()) return;
        lastUiRefreshMs=now;
        updateUiFpsLabel();
        setCurrentFields(readWasmState());
        updateProgressMonitor();
        updateElapsedTimer();
        updateLogInfo();
    }

    // x72 remains meaningful for the paced JavaScript emulator. While WASM
    // owns the CPU there is no selected-clock throttle, so show infinity and
    // restore the exact previous indicator state on pause/handback.
    function setWasmSpeedIndicator(active)
    {
        var indicator=$("slider_1v");
        if(!indicator) return;

        if(active)
        {
            if(!speedIndicatorBackup)
            {
                speedIndicatorBackup={
                    html:indicator.innerHTML,
                    title:indicator.title||"",
                    aria:indicator.getAttribute("aria-label"),
                    backgroundColor:indicator.style.backgroundColor,
                    color:indicator.style.color,
                    borderColor:indicator.style.borderColor,
                    unattainable:indicator.getAttribute("data-speed-unattainable")
                };
            }

            indicator.innerHTML="&infin; <i class='fa fa-fighter-jet' title='WASM accelerator'></i>";
            indicator.title="CPU speed: "+String.fromCharCode(0x221e)+". WASM accelerator is running unthrottled.";
            indicator.setAttribute("aria-label",indicator.title);
            indicator.style.backgroundColor="";
            indicator.style.color="";
            indicator.style.borderColor="";
            indicator.removeAttribute("data-speed-unattainable");
            return;
        }

        if(!speedIndicatorBackup) return;
        indicator.innerHTML=speedIndicatorBackup.html;
        indicator.title=speedIndicatorBackup.title;
        if(speedIndicatorBackup.aria===null) indicator.removeAttribute("aria-label");
        else indicator.setAttribute("aria-label",speedIndicatorBackup.aria);
        indicator.style.backgroundColor=speedIndicatorBackup.backgroundColor;
        indicator.style.color=speedIndicatorBackup.color;
        indicator.style.borderColor=speedIndicatorBackup.borderColor;
        if(speedIndicatorBackup.unattainable===null) indicator.removeAttribute("data-speed-unattainable");
        else indicator.setAttribute("data-speed-unattainable",speedIndicatorBackup.unattainable);
        speedIndicatorBackup=null;
    }

    function readJsState()
    {
        if(typeof(apple2plus)!="object"||!apple2plus) throw new Error("Apple II emulator is not initialized.");
        var cpu=apple2plus.cpuObj();
        if(!cpu||typeof(cpu.watch)!="function") throw new Error("JavaScript 6502 state is unavailable.");
        return cpu.watch();
    }

    function readWasmState()
    {
        if(!e) return null;
        return {
            pc:e.cpu_get_pc()&0xffff,
            a:e.cpu_get_a()&0xff,
            x:e.cpu_get_x()&0xff,
            y:e.cpu_get_y()&0xff,
            sp:e.cpu_get_sp()&0xff,
            p:e.cpu_get_p()&0xff,
            lastOpcode:e.cpu_get_last_opcode()&0xff,
            lastOpcodePC:e.cpu_get_last_opcode_pc()&0xffff
        };
    }

    async function ensureWasm()
    {
        if(wasmInstance) return wasmInstance;
        var module=await wasmModulePromise;
        wasmInstance=await WebAssembly.instantiate(module,{});
        e=wasmInstance.exports;
        var ptr=e.get_ram_ptr()>>>0;
        wr=new Uint8Array(e.memory.buffer,ptr,65536);
        return wasmInstance;
    }

    // Fast handoff image: direct-copy the emulator's 48 KiB physical main RAM,
    // then safely sample only the mapped $C000-$FFFF CPU-bus window.
    function captureCpuImage()
    {
        var hw=apple2plus.hwObj();
        var out=new Uint8Array(0x10000);
        var main=hw.safe_flashdump();
        out.set(main.subarray(0,Math.min(main.length,0xC000)),0);
        out.set(hw.safe_dump(0xC000,0xFFFF),0xC000);
        return out;
    }

    function redrawVideo()
    {
        var video=typeof(apple2plus.vidObj)==="function"?apple2plus.vidObj():null;
        var renderer=video&&typeof(video.getActiveRenderer)==="function"?video.getActiveRenderer():video;
        if(renderer&&typeof(renderer.redraw)==="function") renderer.redraw();
    }

    function handBackRam()
    {
        var hw=apple2plus.hwObj();
        if(!wr) return {ioWritesIgnored:0,mappedWrites:0};

        // Existing helper intentionally restores physical main RAM only.
        hw.load_ram64k(wr);

        // $D000-$FFFF may currently be writable language-card memory.  Apply
        // only bytes changed by WASM through the active write map.  Default ROM
        // callbacks are no-ops, so normal ROM remains untouched.
        var mappedWrites=0;
        if(sourceImage)
        {
            for(var addr=0xD000;addr<=0xFFFF;addr++)
            {
                if(wr[addr]===sourceImage[addr]) continue;
                var fn=hw.WR[hw.lineDecode(addr)];
                if(typeof(fn)==="function") { fn(addr,wr[addr]); mappedWrites++; }
            }
        }

        // $C000-$CFFF is device/slot space.  Flat WASM writes there cannot be
        // replayed safely because the WASM core does not model soft-switch or
        // device side effects; count and ignore them deliberately.
        var ioWritesIgnored=0;
        if(sourceImage)
            for(var io=0xC000;io<=0xCFFF;io++) if(wr[io]!==sourceImage[io]) ioWritesIgnored++;

        redrawVideo();
        return {ioWritesIgnored:ioWritesIgnored,mappedWrites:mappedWrites};
    }

    function setJsPaused(paused)
    {
        if(typeof(oEMUI)==="object"&&oEMUI&&typeof(oEMUI.pauseBtn)==="function")
            oEMUI.pauseBtn({id:'pausebutton',class1:'fa-play',class2:'fa-pause',pause:!!paused});
    }

    function closePopup()
    {
        if(typeof(oCOM)!="undefined"&&oCOM.POPUP&&typeof(oCOM.POPUP.off)==="function")
            oCOM.POPUP.off(wrapper_id);
        else if($(wrapper_id)) $(wrapper_id).hidden=true;
    }

    function bytesToBase64(bytes)
    {
        var s='',step=0x8000;
        for(var i=0;i<bytes.length;i+=step)
            s+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(i+step,bytes.length)));
        return btoa(s);
    }

    function createActivityLogger(maxRecords)
    {
        maxRecords=Math.max(1,Math.floor(Number(maxRecords)||32768));
        var lookup=Object.create(null),sequences=Object.create(null),records=[];
        ACTIVITY_MEMBER_TABLE.forEach(function(m){
            lookup[m.pc]=m;
            if(!sequences[m.group]) sequences[m.group]=[];
            sequences[m.group].push(m);
        });
        Object.keys(sequences).forEach(function(key){ sequences[key].sort(function(a,b){return a.step-b.step;}); });

        var groupId=0,groupNextStep=0,groupCount=0,groupRecord=-1,groupPending=[];
        function resetGroup(){ groupId=0;groupNextStep=0;groupCount=0;groupRecord=-1;groupPending=[]; }
        function emitRaw(rec){ if(records.length>=maxRecords)return false;records.push(rec);return true; }
        function emitOrUpdateGroupMarker(){
            if(groupCount<=0)return;
            if(groupRecord<0){
                if(records.length>=maxRecords)return;
                groupRecord=records.length;
                records.push({marker:true,adr:ACTIVITY_GROUP_MARKER_ADR,group:groupId,repeat:groupCount});
            } else records[groupRecord].repeat=groupCount;
        }
        function flushPending(){ groupPending.forEach(emitRaw);resetGroup(); }
        function startGroup(member,rec){
            var seq=sequences[member.group];
            if(!seq||!seq.length||member.step!==0)return false;
            groupId=member.group;groupNextStep=1%seq.length;groupCount=0;groupRecord=-1;groupPending=[rec];
            if(seq.length===1){groupCount=1;groupPending=[];emitOrUpdateGroupMarker();}
            return true;
        }
        function log(rec){
            if(records.length>=maxRecords)return;
            var member=lookup[rec.adr&0xffff];
            if(!member){flushPending();emitRaw(rec);return;}
            if(!groupId){if(!startGroup(member,rec))emitRaw(rec);return;}
            var seq=sequences[groupId],seqLen=seq?seq.length:0;
            if(member.group===groupId&&member.step===groupNextStep&&seqLen>0){
                groupPending.push(rec);groupNextStep=(groupNextStep+1)%seqLen;
                if(groupNextStep===0){groupCount++;groupPending=[];emitOrUpdateGroupMarker();}
                return;
            }
            flushPending();if(!startGroup(member,rec))emitRaw(rec);
        }
        function toBytes(){
            flushPending();
            var bytes=new Uint8Array(records.length*ACTIVITY_RECORD_BYTES);
            for(var i=0,o=0;i<records.length;i++,o+=ACTIVITY_RECORD_BYTES){
                var r=records[i];bytes[o]=r.adr&0xff;bytes[o+1]=(r.adr>>>8)&0xff;
                if(r.marker){
                    var repeat=r.repeat>>>0;
                    bytes[o+2]=r.group&0xff;bytes[o+3]=(r.group>>>8)&0xff;
                    bytes[o+4]=repeat&0xff;bytes[o+5]=(repeat>>>8)&0xff;bytes[o+6]=(repeat>>>16)&0xff;bytes[o+7]=(repeat>>>24)&0xff;
                } else {
                    bytes[o+2]=r.opcode&0xff;bytes[o+3]=r.operand&0xff;bytes[o+4]=(r.operand>>>8)&0xff;
                    bytes[o+5]=r.a&0xff;bytes[o+6]=r.x&0xff;bytes[o+7]=r.y&0xff;bytes[o+8]=r.p&0xff;bytes[o+9]=r.sp&0xff;
                }
            }
            return bytes;
        }
        return {log:log,get count(){return records.length;},get full(){return records.length>=maxRecords;},get maxRecords(){return maxRecords;},toBytes:toBytes,toBase64:function(){return bytesToBase64(toBytes());}};
    }

    function loggerConfigFromUI(reset)
    {
        loggerEnabled=$("wasm_log_enabled")?$("wasm_log_enabled").checked:false;
        if(!loggerEnabled)
        {
            loggerActive=false;loggerArmed=false;
            return;
        }
        loggerStart=parseOptionalAddress($("wasm_log_start")?$("wasm_log_start").value:"");
        loggerStop=parseOptionalAddress($("wasm_log_stop")?$("wasm_log_stop").value:"");
        if(reset||!activityLogger)
        {
            activityLogger=createActivityLogger(parsePositive("wasm_log_size",32768));
            lastActivityLog=activityLogger;
            loggerArmed=loggerStart!==null;
            loggerActive=!loggerArmed;
            loggerComplete=false;
            loggedSinceYield=0;
        }
        updateLogInfo();
    }

    function updateLogInfo()
    {
        var info=$("wasm_log_info"),download=$("wasm_download_log");
        var count=activityLogger?activityLogger.count:0;
        if(download) download.disabled=!activityLogger||count===0;
        if(!info) return;
        if(!loggerEnabled&&activityLogger) info.textContent="Logger disabled; "+count.toLocaleString()+" captured record(s) retained.";
        else if(!loggerEnabled) info.textContent="Logger disabled.";
        else if(loggerArmed) info.textContent="Logger armed for "+hex(loggerStart,4)+"; "+count.toLocaleString()+" record(s).";
        else if(loggerActive) info.textContent="Logging: "+count.toLocaleString()+" / "+activityLogger.maxRecords.toLocaleString()+" record(s).";
        else if(loggerComplete) info.textContent="Logging complete: "+count.toLocaleString()+" record(s).";
        else info.textContent=count.toLocaleString()+" record(s).";
    }

    function currentRunStop()
    {
        return parseOptionalAddress($("wasm_stop")?$("wasm_stop").value:"");
    }

    function chooseDynamicEscape()
    {
        var runStop=currentRunStop();

        // When the logger is merely armed and there is no competing runner
        // stop, the WASM escape comparator gets us to the logging start at
        // full speed.  With two different pending addresses we single-step in
        // the wrapper so neither condition can be skipped.
        if(loggerEnabled&&loggerArmed&&loggerStart!==null)
        {
            if(runStop===null||runStop===loggerStart) return loggerStart;
            return runStop;
        }

        // While logging we already execute one instruction per wrapper call,
        // so loggerStop is observed in JavaScript.  Keep the hardware handback
        // stop in WASM as an additional pre-fetch guard.
        if(loggerEnabled&&loggerActive) return runStop;
        return runStop;
    }

    function applyDynamicEscape(force)
    {
        if(!e) return;
        var next=chooseDynamicEscape();
        if(!force&&next===dynamicEscape) return;
        dynamicEscape=next;
        var s=readWasmState();
        e.cpu_set_state(s.pc,s.a,s.x,s.y,s.sp,s.p,next===null?0:next,next===null?0:1);
    }

    function logCurrentInstruction()
    {
        if(!loggerEnabled||!loggerActive||!activityLogger||activityLogger.full) return;
        var s=readWasmState(),pc=s.pc&0xffff;
        var opcode=wr[pc]&0xff,len=INSTRLEN[opcode]||1,operand=0;
        if(len>1) operand=wr[(pc+1)&0xffff];
        if(len>2) operand|=wr[(pc+2)&0xffff]<<8;
        activityLogger.log({adr:pc,opcode:opcode,operand:operand,a:s.a,x:s.x,y:s.y,p:s.p,sp:s.sp});
        if(activityLogger.full){loggerActive=false;loggerComplete=true;updateLogInfo();}
    }

    function handleEscapeControl()
    {
        var pc=readWasmState().pc&0xffff;
        var runStop=currentRunStop();
        if(runStop!==null&&pc===runStop) return "handoff";
        if(loggerEnabled&&loggerArmed&&loggerStart!==null&&pc===loggerStart)
        {
            loggerArmed=false;loggerActive=true;loggerComplete=false;dynamicEscape=null;updateLogInfo();return "continue";
        }
        if(loggerEnabled&&loggerActive&&loggerStop!==null&&pc===loggerStop)
        {
            loggerActive=false;loggerComplete=true;dynamicEscape=null;updateLogInfo();return "continue";
        }
        return "handoff";
    }

    function updateButtons()
    {
        var play=$("wasm_play"),pause=$("wasm_pause"),stop=$("wasm_stop_btn"),latch=$("wasm_latch"),copy=$("wasm_copy_regs"),chunk=$("wasm_chunk");
        if(play){play.disabled=phase==="running"||phase==="armed";play.title=phase==="paused"?"Resume WASM":"Run / arm WASM";}
        if(pause) pause.disabled=phase!=="running";
        if(stop) stop.disabled=phase==="idle";
        if(latch) latch.disabled=phase==="running"||phase==="armed";
        if(copy) copy.disabled=phase==="running"||phase==="armed";
        // Chunk changes are intentionally accepted only while idle or paused.
        // Resume will latch the edited value into runChunkInstructions.
        if(chunk) chunk.disabled=phase==="running"||phase==="armed";
    }

    async function runLoop()
    {
        phase="running";pauseRequested=false;stopRequested=false;updateButtons();
        runChunkInstructions=parseChunkInstructions();
        startRunTimer();
        resetProgressEstimate();
        setWasmSpeedIndicator(true);
        lastUiRefreshMs=0;
        refreshWasmUi(true);
        setStatus("WASM running…");
        var maxInstructions=parseLimit();

        while(phase==="running")
        {
            if(stopRequested){await finishHandoff("manual stop");return;}
            if(pauseRequested)
            {
                pauseRunTimer();
                phase="paused";
                pauseRequested=false;
                refreshWasmUi(true);
                setWasmSpeedIndicator(false);
                updateButtons();
                setStatus("WASM paused after "+sessionInstructions.toLocaleString()+" instruction(s).");
                return;
            }
            if(maxInstructions>0&&sessionInstructions>=maxInstructions){await finishHandoff("instruction limit");return;}

            // Observe all wrapper-level addresses before opcode fetch.  The
            // runner stop is exclusive, matching the WASM core escape rule.
            var pcNow=readWasmState().pc&0xffff;
            var runStop=currentRunStop();
            if(runStop!==null&&pcNow===runStop){await finishHandoff("escape "+hex(pcNow,4));return;}
            if(loggerEnabled&&loggerArmed&&loggerStart!==null&&pcNow===loggerStart)
            {
                loggerArmed=false;loggerActive=true;loggerComplete=false;dynamicEscape=null;updateLogInfo();
            }
            if(loggerEnabled&&loggerActive&&loggerStop!==null&&pcNow===loggerStop)
            {
                loggerActive=false;loggerComplete=true;dynamicEscape=null;updateLogInfo();
            }

            applyDynamicEscape(false);
            var reason=0,executed=0;
            var competingArmedStops=loggerEnabled&&loggerArmed&&runStop!==null&&runStop!==loggerStart;
            var singleStep=(loggerEnabled&&loggerActive&&activityLogger&&!activityLogger.full)||competingArmedStops;

            if(singleStep)
            {
                if(loggerEnabled&&loggerActive&&activityLogger&&!activityLogger.full) logCurrentInstruction();
                // The record may have filled the non-ring buffer.  The current
                // instruction is still executed, then fast execution resumes.
                reason=e.cpu_run_chunk(1)>>>0;
                executed=e.cpu_get_last_executed()>>>0;
                sessionInstructions+=executed;
                loggedSinceYield+=executed;
            }
            else
            {
                var chunk=runChunkInstructions;
                var thisChunk=chunk;
                if(maxInstructions>0) thisChunk=Math.min(thisChunk,Math.max(0,maxInstructions-sessionInstructions));
                if(thisChunk<=0){await finishHandoff("instruction limit");return;}
                reason=e.cpu_run_chunk(thisChunk>>>0)>>>0;
                executed=e.cpu_get_last_executed()>>>0;
                sessionInstructions+=executed;
                loggedSinceYield=chunk;
            }

            if(reason===1)
            {
                if(handleEscapeControl()==="handoff"){await finishHandoff("escape "+hex(readWasmState().pc,4));return;}
                applyDynamicEscape(true);
                continue;
            }
            if(reason===2){await finishHandoff("WASM stop");return;}
            if(reason===3){var s=readWasmState();await finishHandoff("illegal opcode "+hex(s.lastOpcode,2)+" at "+hex(s.lastOpcodePC,4),true);return;}

            var yieldEvery=runChunkInstructions;
            if(loggedSinceYield>=yieldEvery)
            {
                loggedSinceYield=0;
                refreshWasmUi(false);
                await nextTick();
            }
        }
    }

    async function beginHandoff()
    {
        try
        {
            setJsPaused(true);
            var jsState=readJsState();
            setCurrentFields(jsState);
            await ensureWasm();
            sourceImage=captureCpuImage();
            wr.set(sourceImage);
            sessionInstructions=0;
            dynamicEscape=null;
            resetRunTimer();
            loggerConfigFromUI(true);

            var runStop=currentRunStop();
            e.cpu_set_state(jsState.pc&0xffff,jsState.a&0xff,jsState.x&0xff,jsState.y&0xff,jsState.sp&0xff,jsState.p&0xff,
                runStop===null?0:runStop,runStop===null?0:1);
            applyDynamicEscape(true);
            await runLoop();
        }
        catch(err)
        {
            console.error("WASM accelerator failed",err);
            setWasmSpeedIndicator(false);
            pauseRunTimer();
            resetRunTimer();
            phase="idle";updateButtons();setStatus(err&&err.stack?err.stack:String(err),"bad");
            setJsPaused(false);
        }
    }

    async function finishHandoff(reason,isError)
    {
        if(phase==="idle") return;
        pauseRunTimer();
        phase="idle";pauseRequested=false;stopRequested=false;
        var state=readWasmState();
        var copy=handBackRam();
        var cpu=apple2plus.cpuObj();
        if(typeof(cpu.setState)==="function") cpu.setState(state);
        else if(typeof(cpu.load)==="function") cpu.load([state.a,state.x,state.y,state.sp,state.p,state.pc].map(function(v){return v.toString(16);}).join(','));
        setWasmSpeedIndicator(false);
        setCurrentFields(state);
        updateProgressMonitor();
        updateLogInfo();updateButtons();

        var msg="WASM finished: "+reason+"; "+sessionInstructions.toLocaleString()+" instruction(s).";
        if(copy.ioWritesIgnored) msg+=" WARNING: "+copy.ioWritesIgnored+" write(s) in $C000-$CFFF were ignored.";
        setStatus(msg,isError?"bad":"good");
        if(copy.ioWritesIgnored) console.warn(msg);

        if(typeof(apple2plus.CPU_pace_reset)==="function") apple2plus.CPU_pace_reset();
        setJsPaused(false);
        resetRunTimer();
        closePopup();
    }

    this.html=function(body_id,popup_id)
    {
        wrapper_id=popup_id||wrapper_id;
        if(typeof(oCOM)!="undefined"&&oCOM.POPUP) oCOM.POPUP.set_state(wrapper_id,true);
        var reg=function(id,label,ro){return "<label style='font-size:9px;text-align:center'>"+label+"<input id='"+id+"' size='4' value='00' "+(ro?"readonly":"")+" style='width:35px;padding:2px;font-size:9px'></label>";};
        return "<div class=appbox style='text-align:left;width:330px;padding:3px;font-family:arial;font-size:10px'>"
            +"<div><b>WASM ACCELERATOR</b> <i class='fa fa-fighter-jet'></i>"
            +"<div class='appbut' onclick=\"oEMU.component.CPU.WASM6502.cancel();\" style='text-align:center;float:right'>x</div></div>"
            +"<div style='display:flex;gap:3px;align-items:end;margin-top:4px'>"
              +"<label>Start<br><input id='wasm_start' size='5' placeholder='immediate' style='width:55px;padding:2px'></label>"
              +"<label>Stop/escape<br><input id='wasm_stop' size='5' placeholder='manual' style='width:55px;padding:2px'></label>"
              +"<label>Chunk (M)<br><span style='display:flex;gap:3px;align-items:center'><input id='wasm_chunk' size='5' value='50' title='Millions of instructions per WASM chunk. Editable while idle or paused; Resume applies the new value.' style='width:42px;padding:2px'><span id='wasm_ui_fps' title='WASM register/progress UI refresh rate' style='font-size:9px;white-space:nowrap'>2 fps</span></span></label>"
              +"<label>Limit<br><input id='wasm_limit' size='6' value='0' title='0 = unlimited' style='width:52px;padding:2px'></label>"
            +"</div>"
            +"<div style='display:grid;grid-template-columns:62px 1fr;gap:4px;align-items:end;margin-top:4px'>"
              +"<label>Progress addr<br><input id='wasm_progress_addr' size='5' value='7FFF' onchange='oEMU.component.CPU.WASM6502.progressChanged()' title='optional 6502 byte address, interpreted as 0..255' style='width:55px;padding:2px'></label>"
              +"<div>"
                +"<div style='display:flex;gap:4px;align-items:center;white-space:nowrap'><progress id='wasm_progress_bar' max='255' value='0' style='width:120px;height:12px'></progress><span id='wasm_progress_text' style='font-variant-numeric:tabular-nums'>0.0%</span><span id='wasm_eta' style='font-size:9px;font-variant-numeric:tabular-nums'>ETA --:--:--</span></div>"
                +"<div style='margin-top:1px;font-size:9px;font-variant-numeric:tabular-nums'>Time <span id='wasm_elapsed'>00:00:00</span></div>"
              +"</div>"
            +"</div>"
            +"<div style='margin-top:5px'><b>Latch</b><div style='display:grid;grid-template-columns:repeat(6,1fr);gap:2px'>"
              +reg("wasm_set_pc","PC",false)+reg("wasm_set_a","A",false)+reg("wasm_set_x","X",false)+reg("wasm_set_y","Y",false)+reg("wasm_set_sp","SP",false)+reg("wasm_set_p","P",false)+"</div></div>"
            +"<div style='margin-top:3px'><b>CPU</b><div style='display:grid;grid-template-columns:repeat(6,1fr);gap:2px'>"
              +reg("wasm_cur_pc","PC",true)+reg("wasm_cur_a","A",true)+reg("wasm_cur_x","X",true)+reg("wasm_cur_y","Y",true)+reg("wasm_cur_sp","SP",true)+reg("wasm_cur_p","P",true)+"</div></div>"
            +"<div style='margin-top:4px'>"
              +"<button class='appbut skinny' id='wasm_copy_regs' onclick='oEMU.component.CPU.WASM6502.copyCurrentToLatch()' title='copy current CPU registers to latch'><i class='fa fa-copy'></i></button> "
              +"<button class='appbut skinny' id='wasm_latch' onclick='oEMU.component.CPU.WASM6502.latchRegisters()' title='latch edited registers into current CPU'><i class='fa fa-sign-in-alt'></i></button> "
              +"<button class='appbut skinny' id='wasm_play' onclick='oEMU.component.CPU.WASM6502.play()' title='run / arm WASM'><i class='fa fa-play'></i></button> "
              +"<button class='appbut skinny' id='wasm_pause' onclick='oEMU.component.CPU.WASM6502.pause()' title='pause WASM'><i class='fa fa-pause'></i></button> "
              +"<button class='appbut skinny' id='wasm_stop_btn' onclick='oEMU.component.CPU.WASM6502.stop()' title='stop WASM and return to JavaScript CPU'><i class='fa fa-stop'></i></button>"
            +"</div>"
            +"<div style='border-top:1px solid #aaa;margin-top:5px;padding-top:4px;display:grid;grid-template-columns:1fr auto;gap:3px 6px;align-items:center'>"
              +"<label style='display:inline-flex;align-items:center;gap:2px;white-space:nowrap'><input id='wasm_log_enabled' type='checkbox' onchange='oEMU.component.CPU.WASM6502.loggerChanged()'> <i class='fa fa-coffee' title='WASM CPU trace'></i> trace</label>"
              +"<div style='display:flex;gap:4px;align-items:center;justify-content:flex-end'>"
                +"<label style='display:inline-flex;align-items:center;gap:2px;white-space:nowrap'>start <input id='wasm_log_start' size='5' placeholder='now' style='width:44px;padding:2px'></label>"
                +"<label style='display:inline-flex;align-items:center;gap:2px;white-space:nowrap'>stop <input id='wasm_log_stop' size='5' placeholder='full' style='width:44px;padding:2px'></label>"
              +"</div>"
              +"<div id='wasm_log_info' style='font-size:9px;line-height:1.15'>Logger disabled.</div>"
              +"<div style='display:flex;gap:4px;align-items:center;justify-content:flex-end'>"
                +"<label style='display:inline-flex;align-items:center;gap:2px;white-space:nowrap'>records <input id='wasm_log_size' size='6' value='32768' style='width:50px;padding:2px'></label>"
                +"<button class='appbut skinny' id='wasm_download_log' disabled onclick='oEMU.component.CPU.WASM6502.downloadLog()' title='download WASM bootlog'><i class='fa fa-shoe-prints'></i></button>"
              +"</div>"
            +"</div>"
            +"<div id='wasm_status' style='margin-top:5px;min-height:24px;font-size:9px;white-space:pre-wrap'>Ready.</div>"
            +"</div>";
    };

    this.open=function()
    {
        try
        {
            setJsPaused(true);
            var state=readJsState();
            setCurrentFields(state);
            updateProgressMonitor();
            this.copyCurrentToLatch();
            resetRunTimer();
            phase="idle";updateButtons();updateLogInfo();
            setStatus("JavaScript CPU halted. Press play to start immediately, or enter a Start address to arm the handoff.");
        }
        catch(err){setStatus(String(err),"bad");}
    };

    this.cancel=function()
    {
        var cpu=typeof(apple2plus)==="object"&&apple2plus?apple2plus.cpuObj():null;
        if(cpu&&typeof(cpu.clearExecutionTrap)==="function") cpu.clearExecutionTrap();
        if(phase==="running"){stopRequested=true;return;}
        if(phase==="paused"){this.stop();return;}
        setWasmSpeedIndicator(false);
        phase="idle";updateButtons();setJsPaused(false);
        resetRunTimer();
        closePopup();
    };

    this.play=function()
    {
        try
        {
            if(phase==="paused")
            {
                loggerConfigFromUI(false);
                applyDynamicEscape(true);
                runLoop();
                return;
            }
            if(phase!=="idle") return;

            var start=parseOptionalAddress($("wasm_start")?$("wasm_start").value:"");
            var cpu=apple2plus.cpuObj();
            var current=cpu.watch().pc&0xffff;

            if(start!==null&&current!==start)
            {
                if(typeof(cpu.setExecutionTrap)!=="function") throw new Error("JavaScript CPU does not provide setExecutionTrap().");
                phase="armed";updateButtons();
                cpu.setExecutionTrap(start,function(){
                    setJsPaused(true);
                    phase="idle";
                    setTimeout(function(){beginHandoff();},0);
                    return true;
                });
                setStatus("WASM armed. JavaScript CPU running until "+hex(start,4)+".");
                setJsPaused(false);
                return;
            }
            beginHandoff();
        }
        catch(err){setStatus(err&&err.stack?err.stack:String(err),"bad");}
    };

    this.pause=function(){ if(phase==="running"){pauseRequested=true;setStatus("Pause requested; waiting for current WASM chunk to finish…");} };
    this.stop=function()
    {
        if(phase==="armed")
        {
            var cpu=apple2plus.cpuObj();if(cpu&&typeof(cpu.clearExecutionTrap)==="function")cpu.clearExecutionTrap();
            phase="idle";updateButtons();setJsPaused(false);closePopup();return;
        }
        if(phase==="running"){stopRequested=true;setStatus("Stop requested; waiting for current WASM chunk to finish…");return;}
        phase="idle";updateButtons();setJsPaused(false);resetRunTimer();closePopup();return;
    };

    this.copyCurrentToLatch=function()
    {
        var s=phase==="paused"&&e?readWasmState():readJsState();
        setCurrentFields(s);
        var vals={pc:[s.pc,4],a:[s.a,2],x:[s.x,2],y:[s.y,2],sp:[s.sp,2],p:[s.p,2]};
        Object.keys(vals).forEach(function(k){var el=$("wasm_set_"+k);if(el)el.value=toHex(vals[k][0],vals[k][1]);});
    };

    this.latchRegisters=function()
    {
        try
        {
            var state={pc:parseWord("wasm_set_pc",0),a:parseByte("wasm_set_a",0),x:parseByte("wasm_set_x",0),y:parseByte("wasm_set_y",0),sp:parseByte("wasm_set_sp",0xFD),p:parseByte("wasm_set_p",0x24)};
            if(phase==="paused"&&e)
            {
                var esc=chooseDynamicEscape();
                e.cpu_set_state(state.pc,state.a,state.x,state.y,state.sp,state.p,esc===null?0:esc,esc===null?0:1);
                dynamicEscape=esc;setCurrentFields(readWasmState());setStatus("Latch values written to paused WASM CPU.");
            }
            else if(phase==="idle")
            {
                var cpu=apple2plus.cpuObj();
                if(typeof(cpu.setState)==="function") cpu.setState(state);
                else cpu.load([state.a,state.x,state.y,state.sp,state.p,state.pc].map(function(v){return v.toString(16);}).join(','));
                setCurrentFields(cpu.watch());setStatus("Latch values written to JavaScript CPU.");
            }
        }
        catch(err){setStatus(String(err),"bad");}
    };

    this.loggerChanged=function()
    {
        try
        {
            var enabled=$("wasm_log_enabled")?$("wasm_log_enabled").checked:false;
            if(phase==="paused"&&enabled&&!loggerEnabled) loggerConfigFromUI(true);
            else if(phase==="paused"&&!enabled){loggerEnabled=false;loggerActive=false;loggerArmed=false;updateLogInfo();}
            else updateLogInfo();
        }
        catch(err){setStatus(String(err),"bad");}
    };

    this.progressChanged=function()
    {
        resetProgressEstimate();
        updateProgressMonitor();
    };

    this.downloadLog=function()
    {
        var log=lastActivityLog||activityLogger;
        if(!log||log.count===0) return;
        var base64=log.toBase64();
        var filename="apple2_wasm_bootlog_"+new Date().toISOString().replace(/[:.]/g,"-")+".txt";
        var blob=new Blob([base64],{type:"text/plain;charset=utf-8"});
        var url=URL.createObjectURL(blob),a=document.createElement("a");
        a.href=url;a.download=filename;a.style.display="none";document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);
    };

    this.getState=function(){return {phase:phase,instructions:sessionInstructions,activityRecords:activityLogger?activityLogger.count:0};};
}