"""Deterministic, offline asset builder; build with clang/wasm-ld 18."""
from pathlib import Path
import base64, hashlib
root=Path(__file__).resolve().parent
fingerprint=hashlib.sha256(b''.join((root/name).read_bytes() for name in ['ay_core.c','ay_core.h','wasm_adapter.js','build.sh','embed.py'])).hexdigest()
binary=(root/'ay_core.wasm').read_bytes()
asset='// Generated by tools/ay_core/build.sh. Do not edit.\nvar AYCoreWASMAsset = {abiVersion:1,sourceSHA256:"'+fingerprint+'",base64:"'+base64.b64encode(binary).decode()+'"};\n'
(root/'../../res/EMU_CHIP_AY_WASM.js').write_text(asset+(root/'wasm_adapter.js').read_text())
