from pathlib import Path
p=Path('res/EMU_CARD_LIRON.js')
s=p.read_text()
s=s.replace('function SmartPortBus()\n{\n    var devices = [];','function SmartPortBus()\n{\n    var bDebug = false;\n    var devices = [];',1)
marker='    var tx=[];\n    var txIndex=0;\n    var lastError="";\n'
insert='''    var tx=[];\n    var txIndex=0;\n    var lastError="";\n\n    const SMARTPORT_COMMAND_NAMES={0x00:"STATUS",0x01:"READ BLOCK",0x02:"WRITE BLOCK",0x03:"FORMAT",0x04:"CONTROL",0x05:"INIT",0x06:"OPEN",0x07:"CLOSE"};\n    function debugLog(event,fields)\n    {\n        if(!bDebug) return;\n        console.log("[LIRON SmartPort] "+event,fields || {});\n    }\n'''
assert marker in s
s=s.replace(marker,insert,1)
s=s.replace('    function buildResponse(source,status,payload)\n    {','''    function buildResponse(source,status,payload)\n    {\n        debugLog("TX_RESPONSE",{"src":source&0x7F,"dest":0,"type":1,"status":status&0x7F,"statusHex":"$"+(status&0x7F).toString(16).toUpperCase().padStart(2,"0"),"payloadLength":payload ? payload.length : 0,"payloadPreview":payload ? Array.from(payload).slice(0,32) : []});''',1)
s=s.replace('    function failPacket(message)\n    {','''    function failPacket(message)\n    {\n        debugLog("PROTOCOL_ERROR",{"reason":message,"protocolState":protocolState,"header":header.slice(),"rxLength":rx.length,"expectedLength":expectedLength});''',1)
s=s.replace('        var command=payload.length ? payload[0]&0x7F : 0;\n','''        var command=payload.length ? payload[0]&0x7F : 0;\n        debugLog("RX_COMMAND",{"dest":dest,"command":command,"commandName":SMARTPORT_COMMAND_NAMES[command] || "UNKNOWN","payload":payload.slice(),"parameterCount":payload.length>1 ? payload[1]&0xFF : null,"residentUnit":findUnitByResidentID(dest) || null});\n''',1)
s=s.replace('            residentIDs[unit]=dest;\n            buildResponse(dest,hasUnassignedUnit()?0x00:0x7F,[]);','''            residentIDs[unit]=dest;\n            debugLog("INIT",{"dest":dest,"assignedUnit":unit,"residentID":dest,"remainingUnassigned":hasUnassignedUnit(),"responseStatus":hasUnassignedUnit()?0x00:0x7F});\n            buildResponse(dest,hasUnassignedUnit()?0x00:0x7F,[]);''',1)
old='''            var readReply=readDevice.readBlock(blockNumber);\n            var readError=readReply && readReply.error!==undefined\n                ? Number(readReply.error)&0x7F : 0x27;\n            var readData=readReply && readReply.data ? Array.from(readReply.data) : [];\n            buildResponse(dest,readError,readData);'''
new='''            var readState=typeof(readDevice.getState)==="function" ? readDevice.getState() || {} : {};\n            debugLog("READ_BLOCK",{"dest":dest,"residentUnit":readUnit,"payload":payload.slice(),"parameterCount":payload.length>1 ? payload[1]&0xFF : null,"bufferAddress":payload.length>3 ? ((payload[2]&0xFF)|((payload[3]&0xFF)<<8)) : null,"blockBytes":[payload.length>4?payload[4]&0xFF:null,payload.length>5?payload[5]&0xFF:null,payload.length>6?payload[6]&0xFF:null],"blockNumber":blockNumber,"mediaLoaded":!!readState.mediaLoaded,"mediaFilename":readState.mediaFilename || ""});\n            var readReply=readDevice.readBlock(blockNumber);\n            var readError=readReply && readReply.error!==undefined ? Number(readReply.error)&0x7F : 0x27;\n            var readData=readReply && readReply.data ? Array.from(readReply.data) : [];\n            debugLog("DEVICE_RESULT",{"command":"READ BLOCK","unit":readUnit,"blockNumber":blockNumber,"error":readError,"errorHex":"$"+readError.toString(16).toUpperCase().padStart(2,"0"),"dataLength":readData.length,"mediaLoaded":!!readState.mediaLoaded,"mediaFilename":readState.mediaFilename || ""});\n            buildResponse(dest,readError,readData);'''
assert old in s
s=s.replace(old,new,1)
s=s.replace('        var frameUnit=payload.length>2 ? payload[2]&0xFF : 0;\n        var statusCode=payload.length>4 ? payload[4]&0xFF : 0;','''        var frameUnit=payload.length>2 ? payload[2]&0xFF : 0;\n        var statusCode=payload.length>4 ? payload[4]&0xFF : 0;\n        debugLog("STATUS",{"dest":dest,"residentUnit":findUnitByResidentID(dest)||null,"frameUnit":frameUnit,"statusCode":statusCode});''',1)
s=s.replace('        var wireChecksum=(c0&0x55)|((c1&0x55)<<1);\n        if(wireChecksum!==checksum)\n        {','''        var wireChecksum=(c0&0x55)|((c1&0x55)<<1);\n        if(wireChecksum!==checksum)\n        {\n            debugLog("CHECKSUM_ERROR",{"expected":checksum,"received":wireChecksum,"header":header.slice(),"payload":payload.slice(),"encodedPayload":encoded.slice()});''',1)
s=s.replace('        lastError="";\n        dispatchPacket(header.slice(),payload);','''        lastError="";\n        debugLog("RX_PACKET",{"dest":header[0]&0x7F,"src":header[1]&0x7F,"type":header[2]&0x7F,"aux":header[3]&0x7F,"status":header[4]&0x7F,"oddCount":header[5]&0x7F,"groupCount":header[6]&0x7F,"rawHeader":header.slice(),"encodedPayload":encoded.slice(),"payload":payload.slice(),"checksumExpected":checksum,"checksumReceived":wireChecksum});\n        dispatchPacket(header.slice(),payload);''',1)
pub='    this.reset = function()\n    {'
assert pub in s
s=s.replace(pub,'    this.setDebug = function(value) { bDebug=!!value; return bDebug; };\n    this.getDebug = function() { return bDebug; };\n\n    this.reset = function()\n    {',1)
card='    this.getBus = function() { return smartport; };\n'
assert card in s
s=s.replace(card,'    this.getBus = function() { return smartport; };\n    this.setDebug = function(value) { return smartport.setDebug(value); };\n    this.getDebug = function() { return smartport.getDebug(); };\n',1)
p.write_text(s)
